//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MyRestTestApplication.EntityJson
{
    public partial class SG_AgenteJson
    {

        public int IdAgente { get; set; }
        public Nullable<int> IdGrupo { get; set; }
        public Nullable<int> IdOrganizacion { get; set; }
        public Nullable<int> TipoAgente { get; set; }
        public string CodigoAgente { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<int> IndicadorMultiple { get; set; }
        public string Clave { get; set; }
        public Nullable<int> ExpiraClave { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<System.DateTime> FechaExpiracion { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }

        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Plataforma { get; set; }

        public string utilClient { get; set; }
  
    }
    
}
